// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6fK5pOxN3lsaVmX_72iopNEP-vBV6GTI',
    appId: '1:168795837419:web:e72fdb855b92091c83bfae',
    messagingSenderId: '168795837419',
    projectId: 'loven-88b0a',
    authDomain: 'loven-88b0a.firebaseapp.com',
    storageBucket: 'loven-88b0a.firebasestorage.app',
    measurementId: 'G-3BP243NL77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGR1gxZYnbvPedCDnFWhTRm3WsoW0MZx8',
    appId: '1:168795837419:android:5a7fe42628ad489183bfae',
    messagingSenderId: '168795837419',
    projectId: 'loven-88b0a',
    storageBucket: 'loven-88b0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIxxB9MYnUiSUsdTeSqwE5L_n7VDe9Cu8',
    appId: '1:168795837419:ios:565adff1e9f3cbca83bfae',
    messagingSenderId: '168795837419',
    projectId: 'loven-88b0a',
    storageBucket: 'loven-88b0a.firebasestorage.app',
    iosBundleId: 'com.five.loven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIxxB9MYnUiSUsdTeSqwE5L_n7VDe9Cu8',
    appId: '1:168795837419:ios:dd247876f084c99083bfae',
    messagingSenderId: '168795837419',
    projectId: 'loven-88b0a',
    storageBucket: 'loven-88b0a.firebasestorage.app',
    iosBundleId: 'com.example.loven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6fK5pOxN3lsaVmX_72iopNEP-vBV6GTI',
    appId: '1:168795837419:web:bfa7f6c3a9a6e07e83bfae',
    messagingSenderId: '168795837419',
    projectId: 'loven-88b0a',
    authDomain: 'loven-88b0a.firebaseapp.com',
    storageBucket: 'loven-88b0a.firebasestorage.app',
    measurementId: 'G-K4EJCTVZ66',
  );
}
