// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfmcziUr2yG1Lgv-zE8rUMzmgUdKIvEt8',
    appId: '1:335940956799:web:42ff64b3e26fd83809854a',
    messagingSenderId: '335940956799',
    projectId: 'loven-24bdd',
    authDomain: 'loven-24bdd.firebaseapp.com',
    storageBucket: 'loven-24bdd.firebasestorage.app',
    measurementId: 'G-XSWGLVYJ56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQBXB-zyRQlSjYmo-ZMwqnQfHqqgLHmxA',
    appId: '1:335940956799:android:84c50c59633eca1909854a',
    messagingSenderId: '335940956799',
    projectId: 'loven-24bdd',
    storageBucket: 'loven-24bdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfFsma666wtqwf4i17D2zNMuNqUZB-Q-s',
    appId: '1:335940956799:ios:71029cf8bb09934a09854a',
    messagingSenderId: '335940956799',
    projectId: 'loven-24bdd',
    storageBucket: 'loven-24bdd.firebasestorage.app',
    iosBundleId: 'com.example.loven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfFsma666wtqwf4i17D2zNMuNqUZB-Q-s',
    appId: '1:335940956799:ios:71029cf8bb09934a09854a',
    messagingSenderId: '335940956799',
    projectId: 'loven-24bdd',
    storageBucket: 'loven-24bdd.firebasestorage.app',
    iosBundleId: 'com.example.loven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfmcziUr2yG1Lgv-zE8rUMzmgUdKIvEt8',
    appId: '1:335940956799:web:e3dfac4982d95fce09854a',
    messagingSenderId: '335940956799',
    projectId: 'loven-24bdd',
    authDomain: 'loven-24bdd.firebaseapp.com',
    storageBucket: 'loven-24bdd.firebasestorage.app',
    measurementId: 'G-XBE2KS24QJ',
  );
}
