name: loven
description: "A full-stack art marketplace app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- State Mangement ---
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # -- Networking & Backend connection ---
  http: ^1.2.0

  # --- Localization & Bilingual support ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # --- UI & Styling ---
  flutter_svg: ^2.0.10+1
  google_fonts: ^8.1.0
  flutter_secure_storage: ^10.0.0

  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Configuration for Flutter Native 
flutter_native_splash:
  color: "#F9F6F0"
  fullscreen: false

  android_12:
    color: "#F9F6F0"

flutter_launcher_icons:
  image_path_android: "assets/images/loven-logo.png"
  image_path_ios: "assets/images/loven-logo.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/loven-logo.png"
  adaptive_icon_foreground: "assets/images/loven-logo.png"
  # --- Flutter Specific Configuration ---
  # --- It must be at the very edge ---
flutter:
  uses-material-design: true

  fonts:
   - family: Almarai
     fonts:
       - asset: assets/fonts/Almarai-Regular.ttf
       - asset: assets/fonts/Almarai-Bold.ttf
         weight: 700

   - family: PT Serif
     fonts:
       - asset: assets/fonts/PTSerif-Regular.ttf
       - asset: assets/fonts/PTSerif-Bold.ttf
         weight: 700     
        
  assets:
    - assets/images/ #For art pieces and backgrounds
    - assets/icons/ # For LOVEN branding
    - assets/fonts/ # For custom SVGs (such as cart, heart, etc.)