services:
# =========================================================================
  # BACKEND SERVICE: The Flask/Python Application
# =========================================================================
  backend:
    build:
      context: ./backend  # Tells Docker to build the image from the Dockerfile in the ./backend directory
    container_name: loven-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db           # Architectural rule: The database starts before the backend server
                     # since PostgreSQL database is heavier, so it needs a few seconde to allocate memory.
    restart: always
# =========================================================================
  # DATABASE SERVICE: PostgreSQL 15 (Alpine)
# =========================================================================
  db:
    image: postgres:15-alpine  # Uses the official, lightweight Alpine version of PostgreSQL 15
    container_name: loven-db
    restart: always
    env_file:
      - ./backend/.env # Reads POSTGRES_USER, PASSWORD, and DB from .env to configure the database
    ports:
      - "5432:5432"  # Exposes the standard Postgres port so tools like SQLTools can connect
    volumes:
      - loven_db_data:/var/lib/postgresql/data # Persists the database data so it isn't lost when the container stops

# ===========================================================================
# VOLUMES: Persistent Storage Declarations
# ===========================================================================
volumes:
  loven_db_data: # Declares the named volume used by the database container above